from __future__ import annotations
import csv, hashlib, json, math
from datetime import datetime, timezone
from pathlib import Path

ROOT=Path(__file__).resolve().parents[2]
OUT=Path(__file__).resolve().parent

def sha(p):
    h=hashlib.sha256()
    with Path(p).open('rb') as f:
        for c in iter(lambda:f.read(1<<20),b''):h.update(c)
    return h.hexdigest()

def loadj(p):return json.loads(Path(p).read_text(encoding='utf-8'))

summary=loadj(OUT/'summary.json')
with (OUT/'pde-scenarios-120.csv').open(encoding='utf-8-sig') as f: scenarios=list(csv.DictReader(f))
split=loadj(OUT/'split-manifest.json')
assert len(scenarios)==120
assert {k:len(v) for k,v in split.items()}=={'train':72,'validation':16,'test':16,'extrapolation':16}
assert summary['CFD']['max_balance_error']<=1e-5
assert all(math.isfinite(float(v)) for section in ('CFD','PINN','SURROGATE','PURE_ML') for v in summary[section].values() if isinstance(v,(int,float)))

inputs=[]
for rel in ['decisions/H2-model.json','04-compute/handoff.json','03-prototype/supplemental-extensions/handoff.json','02-design/supplemental-extensions/handoff.json']:
    inputs.append({'path':rel,'sha256':sha(ROOT/rel)})
outputs=[]
for p in sorted(OUT.rglob('*')):
    if p.is_file() and p.name!='handoff.json': outputs.append({'path':p.relative_to(ROOT).as_posix(),'sha256':sha(p)})
handoff={
 'schema_version':'1.0','stage':'COMPUTE','status':'PASS','scope':'supplemental extensions only; M1-M4 and primary COMPUTE PASS unchanged',
 'inputs':inputs,'outputs':outputs,'frozen_decisions':[inputs[0]],
 'assumptions':['120 labels use genuinely executed low-resolution M3/M4 configurations for comparative screening','CFD and PINN use reduced canonical validation problems'],
 'unknowns':['No independent experimental observations','No full M3/M4 PINN training or industrial 2D/3D multiphase CFD','Surrogate threshold-event safety was not established from full trajectories'],
 'claims':['All 120 PDE scenarios and reported supplementary metrics were generated by the recorded command','Pure ML does not meet threshold-time accuracy needs','The surrogate is promising only for bounded interpolation screening','PINN physical regularization helps the canonical sparse inverse problem','Reduced two-phase CFD is conservative but not yet identifiable for this problem'],
 'warnings':['Do not use supplemental results to replace M1-M4','Measured microsecond inference excludes feature preparation and deployment overhead','PDE-generated labels do not validate real herb drying accuracy'],
 'required_next_actions':['Use these results only as a supplemental comparison section','Require independent phase-resolved or internal observations before promoting CFD/PINN','Require full-trajectory event validation before promoting the surrogate'],
 'completed_at':datetime.now(timezone.utc).astimezone().isoformat()
}
(OUT/'handoff.json').write_text(json.dumps(handoff,ensure_ascii=False,indent=2),encoding='utf-8')
print(json.dumps({'status':'PASS','inputs':len(inputs),'outputs':len(outputs),'handoff_sha256':sha(OUT/'handoff.json')},ensure_ascii=False))
