function render_argument_figures()
root=fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));out=fullfile(root,'06-figure','corrected-20260912');figdir=fullfile(out,'figures');prev=fullfile(out,'previews');if ~isfolder(figdir),mkdir(figdir);end;if ~isfolder(prev),mkdir(prev);end
domain_figure(figdir,prev);hierarchy_figure(figdir,prev);data_figure(root,figdir,prev);moving_figure(figdir,prev);workflow_figure(figdir,prev);fprintf('CORRECTED_ARGUMENT_FIGURES_PASS 5\n');
end
function textbook_schematic(fd,pd)
f=figure('Visible','off','Color','w','InvertHardcopy','off','Units','centimeters','Position',[2 2 16.6 8.8]);ax=axes(f,'Position',[.04 .08 .92 .84]);axis(ax,[0 1 0 1]);axis(ax,'off');hold(ax,'on');
% paired textbook-style states: fixed reference and shrinking moving domain
rectangle(ax,'Position',[.08 .26 .22 .48],'Curvature',[.08 .08],'EdgeColor',[.15 .15 .15],'LineWidth',1.1);plot(ax,[.08 .30],[.50 .50],':','Color',[.35 .35 .35]);plot(ax,[.19 .19],[.26 .74],':','Color',[.35 .35 .35]);text(ax,.19,.80,'初始/参考状态','HorizontalAlignment','center','FontWeight','bold');text(ax,.19,.20,'R(0)=2 cm','HorizontalAlignment','center');text(ax,.205,.57,'z','FontSize',9);text(ax,.28,.53,'r','FontSize',9);annotation(f,'arrow',[.19 .19],[.50 .70],'Color',[.15 .15 .15]);annotation(f,'arrow',[.19 .27],[.50 .50],'Color',[.15 .15 .15]);
rectangle(ax,'Position',[.39 .32 .16 .36],'Curvature',[.08 .08],'EdgeColor',[.15 .15 .15],'LineWidth',1.1);plot(ax,[.39 .55],[.50 .50],':','Color',[.35 .35 .35]);plot(ax,[.47 .47],[.32 .68],':','Color',[.35 .35 .35]);text(ax,.47,.80,'收缩/移动状态','HorizontalAlignment','center','FontWeight','bold');text(ax,.47,.24,'R(t)<R(0)','HorizontalAlignment','center');text(ax,.57,.50,'移动边界','VerticalAlignment','middle');annotation(f,'arrow',[.33 .39],[.50 .50],'Color',[.15 .15 .15]);
% flux/interaction panel
plot(ax,[.75 .75],[.20 .78],'Color',[.15 .15 .15],'LineWidth',1.1);plot(ax,[.68 .82],[.78 .78],'Color',[.15 .15 .15]);plot(ax,[.68 .82],[.20 .20],'Color',[.15 .15 .15]);text(ax,.75,.84,'轴向剖面与边界交换','HorizontalAlignment','center','FontWeight','bold');annotation(f,'arrow',[.62 .72],[.63 .63],'Color',[.15 .15 .15]);text(ax,.64,.66,'q_T','HorizontalAlignment','center');annotation(f,'arrow',[.88 .78],[.51 .51],'Color',[.15 .15 .15]);text(ax,.88,.55,'q_m','HorizontalAlignment','center');annotation(f,'arrow',[.78 .78],[.76 .65],'Color',[.15 .15 .15]);text(ax,.80,.71,'−∂T/∂r','FontSize',8);annotation(f,'arrow',[.78 .78],[.25 .36],'Color',[.15 .15 .15]);text(ax,.80,.30,'−∂C/∂r','FontSize',8);text(ax,.5,.07,'图示采用轴对称坐标；外边界施加热/湿 Robin 交换，Q4 额外引入 R(t) 与 Jacobian 守恒修正。','HorizontalAlignment','center','FontSize',8);savefigs(f,'FIG-MODEL-SCHEMATIC-TEXTBOOK',fd,pd);
end
function [f,ax]=canvas(),f=figure('Visible','off','Color','w','InvertHardcopy','off','Units','centimeters','Position',[2 2 16.6 10.5]);ax=axes(f,'Position',[.05 .07 .9 .88],'Color','w','XColor',[.1 .1 .1],'YColor',[.1 .1 .1]);axis(ax,[0 1 0 1]);axis(ax,'off');hold(ax,'on');set(ax,'FontName','Microsoft YaHei');end
function domain_figure(fd,pd)
[f,ax]=canvas();rectangle(ax,'Position',[.06 .18 .32 .62],'Curvature',[.08 .08],'FaceColor',[.94 .97 1],'EdgeColor',[0 .35 .65],'LineWidth',1.5);plot(ax,[.06 .38],[.49 .49],'--','Color',[.4 .4 .4]);plot(ax,[.22 .22],[.18 .80],':','Color',[.4 .4 .4]);text(ax,.22,.84,'二维轴对称计算域','HorizontalAlignment','center','FontWeight','bold');text(ax,.22,.14,'r=0 轴线：零通量','HorizontalAlignment','center');text(ax,.49,.45,'r=R(t)：Robin 换热/换湿','HorizontalAlignment','center','FontSize',7.5);annotation(f,'arrow',[.38 .49],[.51 .51],'Color',[.84 .37 0]);annotation(f,'arrow',[.22 .22],[.49 .76],'Color',[0 .45 .70]);text(ax,.24,.72,'z');annotation(f,'arrow',[.22 .35],[.49 .49],'Color',[0 .45 .70]);text(ax,.33,.52,'r');
rectangle(ax,'Position',[.61 .22 .23 .55],'Curvature',[.08 .08],'FaceColor',[1 .97 .91],'EdgeColor',[.84 .37 0],'LineWidth',1.5);text(ax,.725,.81,'Q4 收缩域','HorizontalAlignment','center','FontWeight','bold');plot(ax,[.655 .655],[.22 .77],'--','Color',[.84 .37 0]);annotation(f,'arrow',[.77 .70],[.51 .51],'Color',[.84 .37 0]);text(ax,.725,.47,'R(t)↓','HorizontalAlignment','center');text(ax,.725,.16,'移动边界保持干固体连续性','HorizontalAlignment','center');text(ax,.5,.94,'圆柱药材的坐标、边界条件与热湿传递','HorizontalAlignment','center','FontSize',11,'FontWeight','bold');savefigs(f,'FIG-MODEL-DOMAIN',fd,pd);
end
function hierarchy_figure(fd,pd)
[f,ax]=canvas();x=[.03 .27 .51 .75];names={'M1 一维基线','M2 二维主干','M3 状态物性','M4 热湿耦合'};subs={'低成本降阶','端面/轴向效应','D=D(C,T)','内部温度反馈'};for i=1:4,rectangle(ax,'Position',[x(i) .42 .18 .22],'Curvature',.12,'FaceColor',[.92+.015*i .96 .99-.02*i],'EdgeColor',[0 .35 .65],'LineWidth',1.3);text(ax,x(i)+.09,.56,names{i},'HorizontalAlignment','center','FontWeight','bold','FontSize',7.5);text(ax,x(i)+.09,.47,subs{i},'HorizontalAlignment','center','FontSize',7);if i<4,annotation(f,'arrow',[x(i)+.20 x(i+1)-.01],[.53 .53],'Color',[.35 .35 .35]);end,end;text(ax,.5,.82,'统一相容模型层级','HorizontalAlignment','center','FontSize',12,'FontWeight','bold');text(ax,.5,.28,'逐级增加机制；每一级都需通过消融、守恒与收敛检验','HorizontalAlignment','center');annotation(f,'arrow',[.82 .16],[.36 .36],'LineStyle','--','Color',[.84 .37 0]);text(ax,.5,.32,'参数极限下可退化','HorizontalAlignment','center','Color',[.84 .37 0]);savefigs(f,'FIG-MODEL-HIERARCHY',fd,pd);
end
function data_figure(root,fd,pd)
a=readmatrix(fullfile(root,'input','A题','附件','附件1.xlsx'));b=readmatrix(fullfile(root,'input','A题','附件','附件2.xlsx'));a=a(all(isfinite(a),2),:);b=b(all(isfinite(b),2),:);f=figure('Visible','off','Color','w','Units','centimeters','Position',[2 2 34 11.5]);tl=tiledlayout(f,2,2,'Padding','compact','TileSpacing','compact');
tq=linspace(min(a(:,1)),max(a(:,1)),180);idxA=1:max(1,round(size(a,1)/24)):size(a,1);idxB=1:max(1,round(size(b,1)/24)):size(b,1);a1=nexttile(tl);plot(a1,tq/3600,interp1(a(:,1),a(:,2),tq,'linear'),'-','LineWidth',1.3,'DisplayName','分段线性插值');hold(a1,'on');plot(a1,a(idxA,1)/3600,a(idxA,2),'o','MarkerFaceColor','w','MarkerSize',4,'DisplayName','稀疏原始观测');xlabel(a1,'时间 (h)');ylabel(a1,'温度 (°C)');title(a1,'附件1：温度原始点与分段线性插值');xlim(a1,[0 5]);paper(a1);legend(a1,'Location','southeast');
a2=nexttile(tl);plot(a2,tq/3600,interp1(a(:,1),a(:,3),tq,'linear'),'-','LineWidth',1.3,'DisplayName','边界插值');hold(a2,'on');plot(a2,a(idxA,1)/3600,a(idxA,3),'o','MarkerFaceColor','w','MarkerSize',4,'DisplayName','稀疏原始观测');xlabel(a2,'时间 (h)');ylabel(a2,'水汽浓度');title(a2,'附件1：湿度边界处理');xlim(a2,[0 5]);paper(a2);legend(a2,'Location','southeast');
tq2=linspace(min(b(:,1)),max(b(:,1)),180);a3=nexttile(tl);plot(a3,tq2/3600,interp1(b(:,1),b(:,2),tq2,'pchip'),'-','LineWidth',1.3,'DisplayName','PCHIP 重建');hold(a3,'on');plot(a3,b(idxB,1)/3600,b(idxB,2),'o','MarkerFaceColor','w','MarkerSize',4,'DisplayName','稀疏半径观测');xlabel(a3,'时间 (h)');ylabel(a3,'半径 (cm)');title(a3,'附件2：半径观测与 PCHIP 重建');xlim(a3,[0 90]);paper(a3);legend(a3,'Location','northeast');
a4=nexttile(tl);tend=max(a(:,1));ext=[tend tend+4*3600]/3600;plot(a4,tq/3600,interp1(a(:,1),a(:,2),tq,'linear'),'-','LineWidth',1.2,'DisplayName','观测区间（插值线）');hold(a4,'on');idx4=1:max(1,round(size(a,1)/50)):size(a,1);plot(a4,a(idx4,1)/3600,a(idx4,2),'o','MarkerFaceColor','w','MarkerSize',4,'HandleVisibility','off');plot(a4,ext,[a(end,2) a(end,2)],'--','LineWidth',1.5,'DisplayName','冻结延拓');xline(a4,tend/3600,':','4 h延拓起点');xlabel(a4,'时间 (h)');ylabel(a4,'温度边界 (°C)');title(a4,'末段稳健统计量延拓示意');xlim(a4,[0 10]);paper(a4);legend(a4,{'观测区间（插值线）','冻结延拓'},'Location','southeast');savefigs(f,'FIG-DATA-PROCESSING',fd,pd);
fw=figure('Visible','off','Color','w','Units','centimeters','Position',[2 2 34 7]);aw=axes(fw,'Position',[.08 .18 .88 .70]);xobs=a(:,1)/3600;yobs=a(:,2);plot(aw,xobs,yobs,'-o','Color',[0 .447 .698],'LineWidth',1.4,'MarkerIndices',1:12:numel(xobs),'MarkerFaceColor','w','MarkerEdgeColor',[0 .447 .698],'MarkerSize',4,'DisplayName','观测区间（分段线性）');hold(aw,'on');plot(aw,ext,[a(end,2) a(end,2)],'-s','Color',[.835 .369 0],'LineWidth',1.5,'MarkerIndices',[1 2],'MarkerFaceColor','w','MarkerEdgeColor',[.835 .369 0],'MarkerSize',5,'DisplayName','冻结延拓');xlabel(aw,'时间 (h)');ylabel(aw,'温度边界 (°C)');title(aw,'末段稳健统计量延拓示意');xlim(aw,[0 10]);ylim(aw,[25 55]);paper(aw);set(aw,'FontName','SimSun');set(findall(aw,'Type','text'),'FontName','SimSun','Color',[.1 .1 .1]);lg=legend(aw,{'观测区间（分段线性）','冻结延拓'},'Location','southeast','Orientation','vertical','NumColumns',1);set(lg,'FontName','SimSun','TextColor',[0 0 0],'Color','w','Box','on','ItemTokenSize',[18 8]);savefigs(fw,'FIG-DATA-EXTENSION-WIDE',fd,pd);
fz=figure('Visible','off','Color','w','Units','centimeters','Position',[2 2 24 16]);tz=tiledlayout(fz,2,2,'Padding','compact','TileSpacing','compact');xx={a(:,1)/3600,a(:,1)/3600,b(:,1)/3600,a(:,1)/3600};yy={a(:,2),a(:,3),b(:,2),a(:,2)};tt={'温度插值局部放大','湿度边界局部放大','半径 PCHIP 局部放大','延拓起点局部放大'};centers=[.65 .65 .65 .92];for iz=1:4,az=nexttile(tz);x0=xx{iz};y0=yy{iz};c=max(2,min(numel(x0)-1,round(numel(x0)*centers(iz))));ii=(c-1):(c+1);plot(az,x0(ii),y0(ii),'-','LineWidth',1.5);hold(az,'on');plot(az,x0(ii),y0(ii),'o','MarkerFaceColor','w','MarkerSize',7);xlim(az,[min(x0(ii))-0.08*max(1,(max(x0(ii))-min(x0(ii)))),max(x0(ii))+0.08*max(1,(max(x0(ii))-min(x0(ii))))]);ylim(az,[min(y0(ii))-0.12*max(1,(max(y0(ii))-min(y0(ii)))),max(y0(ii))+0.12*max(1,(max(y0(ii))-min(y0(ii))))]);title(az,tt{iz});xlabel(az,'时间 (h)');paper(az);end;savefigs(fz,'FIG-DATA-ZOOM-THREE-POINTS',fd,pd);
end
function moving_figure(fd,pd)
[f,ax]=canvas();th=linspace(0,2*pi,200);styles={'-','--',':'};for k=1:3,r=.24-.055*(k-1);plot(ax,.30+r*cos(th),.50+.62*r*sin(th),'LineWidth',1.3,'LineStyle',styles{k});text(ax,.30+r+.01,.50,sprintf('t_%d',k-1));end;annotation(f,'arrow',[.55 .68],[.67 .67]);text(ax,.615,.71,'r=R(t)ξ','HorizontalAlignment','center');rectangle(ax,'Position',[.70 .28 .20 .44],'FaceColor',[.94 .97 1],'EdgeColor',[0 .35 .65]);plot(ax,[.80 .80],[.28 .72],':');text(ax,.80,.76,'固定参考域 0≤ξ≤1','HorizontalAlignment','center','FontWeight','bold');text(ax,.80,.52,'Jacobian J(t)','HorizontalAlignment','center');text(ax,.80,.42,'网格速度修正','HorizontalAlignment','center');text(ax,.5,.9,'Q4 移动边界映射与守恒修正','HorizontalAlignment','center','FontSize',12,'FontWeight','bold');text(ax,.5,.13,'删除 Jacobian 修正会使归一化平衡误差增至 0.593632（V10 消融失败）','HorizontalAlignment','center','Color',[.84 .37 0]);savefigs(f,'FIG-MOVING-DOMAIN',fd,pd);
end
function workflow_figure(fd,pd)
[f,ax]=canvas();x=.02:.195:.80;names={'附件1/2原始','线性/PCHIP延拓','M1–M4守恒求解','网格/时间/守恒验证','全域阈值夹逼'};for i=1:5,rectangle(ax,'Position',[x(i) .42 .15 .20],'Curvature',.1,'FaceColor',[.94 .97 1],'EdgeColor',[0 .35 .65]);text(ax,x(i)+.075,.52,names{i},'HorizontalAlignment','center','FontWeight','bold','FontSize',7);if i<5,annotation(f,'arrow',[x(i)+.155 x(i+1)-.005],[.52 .52]);end,end;text(ax,.5,.79,'从原始附件到结果文件的数据—模型流程','HorizontalAlignment','center','FontSize',12,'FontWeight','bold');text(ax,.5,.29,'失败分支：72 h未达标、Jacobian消融失败、窄验证裕量均返回证据链','HorizontalAlignment','center','Color',[.84 .37 0]);annotation(f,'arrow',[.88 .15],[.39 .39],'LineStyle','--','Color',[.84 .37 0]);savefigs(f,'FIG-DATA-MODEL-WORKFLOW',fd,pd);
end
function paper(a),set(a,'FontName','Microsoft YaHei','FontSize',8,'Color','w','XColor',[.1 .1 .1],'YColor',[.1 .1 .1],'Box','off','TickDir','out');grid(a,'on');a.GridColor=[.75 .75 .75];a.GridAlpha=.25;end
function savefigs(f,id,fd,pd),if any(strcmp(id,{'FIG-MODEL-DOMAIN','FIG-MODEL-SCHEMATIC-TEXTBOOK','FIG-MODEL-HIERARCHY','FIG-MOVING-DOMAIN','FIG-DATA-MODEL-WORKFLOW'})),mono(f);end;set(findall(f,'Type','text'),'Color',[.1 .1 .1],'FontName','Microsoft YaHei');set(findall(f,'Type','legend'),'Color','w','TextColor',[.1 .1 .1]);exportgraphics(f,fullfile(fd,[id '.svg']),'ContentType','vector');exportgraphics(f,fullfile(fd,[id '.png']),'Resolution',600);exportgraphics(f,fullfile(pd,[id '-preview.png']),'Resolution',160);if strcmp(id,'FIG-DATA-EXTENSION-WIDE'),exportgraphics(f,fullfile(fd,[id '.pdf']),'ContentType','vector');end;close(f);end
function mono(f),set(f,'Color','w');objs=findall(f);for k=1:numel(objs),o=objs(k);try
 if strcmp(get(o,'Type'),'axes'),set(o,'Color','w','XColor',[.1 .1 .1],'YColor',[.1 .1 .1]);end
 if isprop(o,'Color') && ~any(strcmp(get(o,'Type'),{'text','figure','axes'})),set(o,'Color',[.15 .15 .15]);end
 if isprop(o,'EdgeColor'),set(o,'EdgeColor',[.15 .15 .15]);end
 if isprop(o,'FaceColor') && ~strcmp(get(o,'FaceColor'),'none'),set(o,'FaceColor',[.92 .92 .92]);end
 catch,end,end;end

